steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-com-294113/git'
  args: ['clone','https://github.com/mahmad-LU/new-cidc.git']

#Build the image gcr.io/cloud-com-294113/cloud-g8
- name: 'gcr.io/cloud-com-294113/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-com-294113/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-com-294113/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: cloud-com-294113
    _ZONE: us-central1-a
    _GKE_CLUSTER: test-cluster
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: hello-world-service    
    _REPO_NAME: cloud-com
    
    # Developers ONLY change
    _VERSION: $GITHUB_SHA
    
options:
    substitution_option: 'ALLOW_LOOSE'

